### ISSUE TITLE
로그인

### ISSUE THREAD

**Issue by ryu820** [Final-Project-Team11/Meer_catlender_BE#2]
✅사업자 로그인 / 일반 유저 로그인
- 일반 유저는 사업자의 아이디를 회사코드로 사용할 수 있다.
- 사업자 로그인 시 필요한 값은 **아이디, 비밀번호**
- 일반 유저 로그인 시 필요한 값은 **회사코드, 아이디, 비밀번호**
- 일반 유저의 password는 초기값으로 설정되어 있기 때문에 **최초 로그인 시 비밀번호 변경 API 호출**
- 일반 유저가 생성될 때 team, user 테이블에 데이터가 저장되기 때문에 유저의 정보를 쉽게 찾기 위해서 페이로드 값 설정
> payload : { userId, companyId, teamName, authLevel }
- bcrypt 를 사용해서 **비밀번호 암호화** 적용

✅**Trouble Shooting**

문제점 1.
- 유저 로그인 부분이랑 사업자 로그인 부분의 유사성을 이용해서 코드의 재사용을 하려고 했으나 사업자 로그인의 코드를 유저 로그인에서 다시 사용하려고 하니까 키 값이 달라져서 user 정보를 찾을 수 없는 에러 발생
```
 const user = await this.AuthService.checkIdPassword({
                companyId: userId,
                password,
            });
```
해결방법 1.
- 메소드를 하나 새로 만들어서 따로 처리해줌

```
  const user = await this.AuthService.checkUserIdPassword({
        userId,
        password,
    });
```

문제점 2.
- 비밀번호 변경 API 에 Joi를 적용해주면서 req.body의 값의 validation 을 모두 체크해주면서 비밀번호의 정규 표현식도 적용해주어야 하는데 적용을 안해주어서 비밀번호를 변경하면 데이터베이스에 유저가 입력한 비밀번호가 그래도 노출되는 문제 발생

해결 방법 2. 
- 아래처럼 Joi 라이브러리를 사용해서 정규표현식 적용
```
const regex = /^[a-zA-Z0-9]{5,}$/;
        const schema = Joi.object({
            password: Joi.string().min(5).pattern(regex).required().messages({
                "string.base": "pasword 필드는 문자열로 이루어져야 합니다.",
                "string.pattern.base": "비밀번호는 영문 대/소문자와 숫자만 포함 가능합니다.",
                "string.min": "비밀번호는 최소 5글자여야 합니다.",
                "string.empty": "비밀번호를 입력해 주세요.",
                "any.required": "필수입력값을 입력해주세요",
            }),
        });
```

**Comment by SuHyeon-Eleven** [comment]
내가 하고싶엇던..

**Comment by ryu820** [comment]
#214 
API 수정 후 코드 수정 업데이트

**Comment by ryu820** [comment]
- #225

**Comment by ryu820** [comment]
- #330
